### ISSUE TITLE
Vim 8 terminal colours

### ISSUE THREAD

**Issue by ledohod** [jnurmine/Zenburn#30] opened 2020-08-30 12:53 UTC
Hi,

This is a brilliant theme, I have used the Emacs version of it for a long time. I feel like simplifying things and start using Vim. In Vim 8, when I open a terminal within Vim, this colour scheme doesn't apply to it. But other colour themes such as "nord" apply to both the buffers and the terminal buffer.

Thanks.

**Comment by jnurmine** [comment] 2020-08-30 16:41
Hi, thanks for reporting this.

Looks like the `g:terminal_ansi_colors` is not set.

Cheers,
Jani

**Comment by jnurmine** [comment] 2020-08-30 20:52
I'll soon upload a fix with nicer coloring. They have the same color order as the terminal usually has.

The terminal is not tinted towards some specific color (that could be for future work).

Looks like the terminal coloring feature needs Vim 8.2.0+
Please note, it seems one must use "set termguicolors" when running Vim in a terminal.

Please let me know if it works better, closing for now.

Cheers!

**Closed by jnurmine** 2020-08-30 20:52 UTC

**Comment by ledohod** [comment] 2020-08-31 12:54
Hi,

Thanks, the terminal colours are as what is usually in the terminal outside Vim now'. The background is still black. I had the termguicolors set. Also, if you don't mind me saying, the relative line numbers' colouring stands out a little too much a bit distracting, I felt like the line number colours could be muted more and the background of the left gutter be a bit more grey just a shade or two different from the main background.

Thanks.

**Comment by jnurmine** [comment] 2020-08-31 20:13
Hi,

hmm, about the line numbers colouring, you are right.
Now that you pointed it out it is a standing out a bit too much.

I added a switch called `g:zenburn_subdued_LineNr`.

Here is a picture of it enabled in low contrast mode in the GUI:

![image](https://user-images.githubusercontent.com/221556/91763234-e0c83500-ebd5-11ea-8986-a0d93d132bbd.png)

And here in high contrast mode in the GUI:

![image](https://user-images.githubusercontent.com/221556/91763500-f76e8c00-ebd5-11ea-9d4d-439d7e48d63a.png)

**Comment by jnurmine** [comment] 2020-08-31 20:27
PS. I added a fix now for the terminal colouring, use ANSI colors for Vim 8.2.0+, otherwise the older one. It looks like the Terminal highlight group disturbed the background. Now the terminal looks more as intended.

Does the terminal now look as you expected?

**Comment by ledohod** [comment] 2020-09-08 10:18
Sorry for late reply. All looks great now! Except the the highlight of the numbers gutter with `set cursorline`. The current line's number gets underlined with yellow.

**Comment by jnurmine** [comment] 2020-09-08 16:35
Hi, can you please attach a screenshot?

I don't see the underline, with or without `:set cursorline`, I have tried terminal and vim -g for different versions... Do you have some other setting enabled?

**Comment by ledohod** [comment] 2020-09-08 19:24
Here is a screen shot. I launched Vim without the .vimrc, set the colorscheme and then the cursorline. 

![Screenshot from 2020-09-08 20-20-39](https://user-images.githubusercontent.com/38806573/92519028-3a9db000-f211-11ea-8d5d-2407f5214d39.png)

**Comment by jnurmine** [comment] 2020-09-08 22:22
Thanks, I can see it with Vim 8.2:

![image](https://user-images.githubusercontent.com/221556/92532676-13ef7180-f231-11ea-83a8-b9744bc73a78.png)

But with 8.0 no such thing:

![image](https://user-images.githubusercontent.com/221556/92532712-28336e80-f231-11ea-94af-e76ff4f584a6.png)

The syntax file is exactly the same in both cases.

It looks like Vim overrides cterm=underline always, possibly due to commit `017ba07fa2cdc5` in 8.1.2029.

Not sure yet how to solve this, explicitly specifying cterm doesn't help.

**Comment by jnurmine** [comment] 2020-09-08 22:41
Looks like explicit cterm=none works, but the colorscheme must be loaded at Vim startup time i.e. Vim must be restarted for this change to take effeect.

There's a fix now, can you please check if it's OK?

**Comment by ledohod** [comment] 2020-09-09 12:37
Your fix works, thanks. Following your code above, I've put this right at the end of the .vimrc 
```
set cursorline    
highlight CursorLineNR cterm=NONE ctermfg=234 ctermbg=234 guifg=#424242 guibg=#1b1b1b
```
I am trying to make the line highlight not effect the gutter at all, but I can't get the background colour right, I got the colours from your zenburn.vim file. What is the correct background colour for the gutter? Do you know if there is an easier way to disable the highlight in the gutter altogether?

**Comment by jnurmine** [comment] 2020-09-09 16:56
Hi, there should not be need to specify `highlight CursorLineNR` since Zenburn has the `cterm=none` now.

Anyway, you should get a newer Vim, like 8.2 and then do `:set cursorlineopt=line` to avoid highlighting the gutter.

**Comment by ledohod** [comment] 2020-09-09 18:52
Ah, that's great! Thank you so much!
